[ids]
05ac:024f

# Режим F (по умолчанию): F1..F12 = обычные клавиши
[main]
rightcontrol = layer(fn)
brightnessdown = f1
brightnessup = f2
scale = f3
dashboard = f4
kbdillumdown = f5
kbdillumup = f6
previoussong = f7
playpause = f8
nextsong = f9
mute = f10
volumedown = f11
volumeup = f12

# Слой на время удержания FN
[fn]
esc = toggle(media)

# Медиа-режим: F1..F12 = медиа-клавиши
[media]
rightcontrol = layer(fn)
brightnessdown = brightnessdown
brightnessup = brightnessup
scale = scale
dashboard = dashboard
kbdillumdown = kbdillumdown
kbdillumup = kbdillumup
previoussong = previoussong
playpause = playpause
nextsong = nextsong
mute = mute
volumedown = volumedown
volumeup = volumeup